### ISSUE TITLE
Space Traveler's Hub Setup

### ISSUE THREAD

**Issue by melaniesigrid** [melaniesigrid/space_travelers_hub#21]
Hello! Thank you for reviewing our project. There are 2 people in our team: @danielufeli and me @melaniesigrid. 

Here is the link to our Project:
https://github.com/melaniesigrid/space_travelers_hub/projects/1

<img src="https://media2.giphy.com/media/b85mPT4Usz7fq/giphy.gif"/>

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽 @melaniesigrid @danielufeli 

Good job working on the project so far! 
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/l3JDhOnR017YfwIeY/giphy.gif)

## Required Changes ♻️
- [x] There should be 17 cards in total in your backlog but they are currently 13. Kindly go through this [template board](https://github.com/microverseinc/curriculum-react-redux/projects/1) to find the four missing cards and add them.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by melaniesigrid** [comment]
Thank you for your review! We have reviewed and added the missing cards in our project! ⭐

**Comment by julie-ify** [comment]
Hi @melaniesigrid and @danielufeli, 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
